version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - addressbook

  app:
    build: .
    container_name: app
    networks:
      - addressbook
    ports:
      - 1337
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    depends_on:
      - mongodb

networks:
  addressbook:
    driver: bridge
