version: "3"
services:
  db:
    image: mongo
    ports:
      - 27017:27017

  app:
    build: .
    command: npm run dev
    ports:
      - 1337:1337
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    env_file:
      - .env
    environment:
       - MONGODB_URI=mongodb://db/address-book
    links:
      - db
    depends_on:
      - db


